### ISSUE TITLE
Connection closed before full header was received

### ISSUE THREAD

**Issue by timsneath** [SpinlockLabs/github.dart#309]
In GitHub.request, the following line can throw an uncaught exception:

```dart
    final response = await http.Response.fromStream(streamedResponse);
```

Ideally this should be handled...

Here's the stack trace:
```
Connection closed before full header was received
#0      IOClient.send (package:http/src/io_client.dart:66:7)
<asynchronous suspension>
#1      GitHub.request (package:github/src/common/github.dart:400:30)
<asynchronous suspension>
#2      PaginationHelper.fetchStreamed (package:github/src/common/util/pagination.dart:38:20)
<asynchronous suspension>
#3      SearchService.repositories.<anonymous closure> (package:github/src/common/search_service.dart:30:17)
<asynchronous suspension>
```

**Comment by mosuem** [comment]
Any updates on this?
